{{ if .Values.prometheus.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "prometheus-deployment-{{ .Chart.Name }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "prometheus-server-{{ .Chart.Name }}"
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v1.8.2
          args:
            - "-config.file=/etc/prometheus/conf/prometheus.yml"
            - "-storage.local.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/conf/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: "prometheus-config-{{ .Chart.Name }}"
        - name: prometheus-storage-volume
          emptyDir: {}
{{ end }}